apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ic-webapp
  labels:
    app: {{ .Release.Name }}-ic-webapp
    env: {{ .Values.env }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-ic-webapp
  ports:
    - protocol: TCP
      port: {{ .Values.icWebapp.service.port }}
      targetPort: 8080
      nodePort: {{ .Values.icWebapp.service.nodePort }}
