apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.odoo.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    env: {{ .Values.env }}
    app: {{ .Release.Name }}-odoo  
type: Opaque
data:
  PASSWORD: {{ .Values.odoo.secret.password | b64enc | quote }}
