apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-odoo
  labels:
    app: {{ .Release.Name }}-odoo
    env: {{ .Values.env }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-odoo
  ports:
    - protocol: TCP
      port: {{ .Values.odoo.service.port }}
      targetPort: 8069
      nodePort: {{ .Values.odoo.service.nodePort }}
