apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pg-admin
  labels:
    app: {{ .Release.Name }}-pg-admin
    env: {{ .Values.env }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-pg-admin
  ports:
    - protocol: TCP
      port: {{ .Values.pgadmin.service.port }}
      targetPort: {{ .Values.pgadmin.service.targetPort }}
      nodePort: {{ .Values.pgadmin.service.nodePort }}
