apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pgadmin.pv.name }}
  labels:
    type: local
    env: {{ .Values.env }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.pgadmin.pv.storageClassName }}
  capacity:
    storage: {{ .Values.pgadmin.pv.capacity }}
  accessModes:
    - {{ .Values.pgadmin.pv.accessModes | join ", " }}
  hostPath:
    path: {{ .Values.pgadmin.pv.hostPath }}
