apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgadmin.secret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    env: {{ .Values.env }}
    app: {{ .Release.Name }}-pg-admin 
type: Opaque
data:
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.pgadmin.secret.password | b64enc | quote }}
