apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    env: {{ .Values.env }}
    app: {{ .Values.postgres.appName }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgres.secret.password | b64enc | quote }}
